export const GITHUB_GET_USER_BEGIN = 'GITHUB_GET_USER_BEGIN';
export const GITHUB_GET_USER_SUCCESS = 'GITHUB_GET_USER_SUCCESS';
export const GITHUB_GET_USER_FAILURE = 'GITHUB_GET_USER_FAILURE';
export const GITHUB_GET_USER_DISMISS_ERROR = 'GITHUB_GET_USER_DISMISS_ERROR';
